# Generated by Django 4.2.4 on 2023-08-16 01:20

from django.db import migrations, models

def create_initial_ips(apps, schema_editor):
    ip_addr = apps.get_model('core', 'IP_Addresses')
    db = schema_editor.connection.alias
    ip_addr.objects.using(db).bulk_create([
        ip_addr(IP='192.168.1.1'),
        ip_addr(IP='192.168.1.2'),
        ip_addr(IP='192.168.1.3'),
    ])

class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IP_Addresses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IP", models.GenericIPAddressField(protocol="IPv4")),
            ],
        ),
        migrations.RunPython(create_initial_ips)
    ]
