# Generated by Django 4.2.4 on 2023-08-16 02:00

from django.db import migrations, models

def create_initial_ips(apps, schema_editor):
    ip_addr = apps.get_model('core', 'IP_Addresses')
    db = schema_editor.connection.alias
    ip_addr.objects.using(db).bulk_create([
        ip_addr(IP='192.168.1.1'),
        ip_addr(IP='192.168.1.2'),
        ip_addr(IP='192.168.1.3'),
    ])

class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ip_addresses",
            name="IP",
            field=models.GenericIPAddressField(),
        ),
        migrations.RunPython(create_initial_ips)
    ]
