# Generated by Django 4.2.4 on 2023-08-16 02:15

import django.core.validators
from django.db import migrations, models

def create_initial_vlans(apps, schema_editor):
    vlan = apps.get_model('core', 'VLANs')
    db = schema_editor.connection.alias
    vlan.objects.using(db).bulk_create([
        vlan(VID='99'),
        vlan(VID='100'),
        vlan(VID='101'),
    ])
class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_ip_addresses_ip"),
    ]

    operations = [
        migrations.CreateModel(
            name="VLANs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "VID",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4093),
                        ]
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_initial_vlans)
    ]
